# Generated by Django 2.2.2 on 2020-07-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opp', '0003_opportunites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunites',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
