# Generated by Django 2.2.2 on 2020-07-18 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opp', '0005_auto_20200718_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='voteproduct',
            new_name='product',
        ),
    ]
