# Generated by Django 2.2.2 on 2020-07-18 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opp', '0006_auto_20200718_2238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='product',
            new_name='opportunites',
        ),
    ]
