# Generated by Django 2.2.2 on 2020-07-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opp', '0009_auto_20200719_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunites',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
    ]
