# Generated by Django 2.2 on 2020-07-20 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opp', '0010_opportunites_dislikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friend', to='opp.UserProfile'),
        ),
    ]
